### PR TITLE
[extimg] add hdf5 support

### PR DESCRIPTION
**Pull request by woutdenolf**
This PR addresses issue #422 (only the External Images Plugin). Same dataset selection logic as RGB Correlator (PR #502). Except in this case, the data shape seems to be restricted instead of the number of elements (same shape, but allowing for transposition). At least this is the behavior for EDF files so I assume it is also expected for HDF5 datasets.

### CODE REVIEW

**Comment by vasole** [comment]
Silx External Images Tool also needs to access the HDF5 results.

**Comment by vasole** [comment]
It is another Stack plugin.

**Comment by woutdenolf** [comment]
Done. IO routines are shared between the 2 extimg plugins.

**Comment by vasole** [comment]
Currently re-running the tests under MacOS to see if the failure is reproducible.

**Comment by vasole** [comment]
I dislike the use of a metaclass but well...

I think ExternalImagesStackPluginBase.py should be moved to PyMca5.PyMcaGui.pymca

**Pull request merged**
