### PR TITLE
Mask Scatter View plugin

### PR DESCRIPTION
**Pull request by PiRK**
Addresses #346 

The matplotlib backend seems to be close to its limits when displaying the ch09 stack as a scatter.

### CODE REVIEW

**Comment by vasole** [comment]
Yes, I think OpenGL is almost mandatory.

**Comment by PiRK** [comment]
It is almost ready, but still needs to be tested with real positioner data.

What is missing is to update the mask at the same time as the scatter when changing axes. It works if the mask tools widget is shown, but not if it is hidden (no active scatter handling if the widget is hidden).

**Comment by PiRK** [comment]
It can probably be merged as it is. 

The few remaining problems with mask synchronization are hard to fix and are related to performance optimizations: the mask not updated on active scatter/image changes when the mask tool is hidden.
Whether it should synchronized all the time should be discussed on the silx side.

Anyway, the inconvenience is minor, as the mask is now properly drawn at widget initialization, and is properly redrawn whenever any synchronized widget makes any change to the mask. It only is a problem if this widget has the mask tools hidden and the user changes the axis, then the data points may move without the mask points following them.

**Comment by PiRK** [comment]
I think I managed to find a workaround to force synchronization.

**Comment by vasole** [comment]
A cherry on the cake it will be when we can specify background images with their positions and scales.

**Comment by vasole** [comment]
Thanks!

**Comment by PiRK** [comment]
The widget is currently minimalistic, but it could be improved to have a similar API to the `SilxMaskImageWidget`. 

The background image should be simple. But displaying other motor positions associated with each scatter point is not as trivial as with an image.

**Pull request merged**
