### PR TITLE
NXdata new style

### PR DESCRIPTION
**Pull request by PiRK**
Addresses #86

### CODE REVIEW

**Comment by vasole** [comment]
It seems this implementations gives up support of old style signals.

**Comment by vasole** [comment]
I mean when reading.

**Comment by PiRK** [comment]
Yes, you're right. My Mistake. The latest commit fixes this. If there is a signal attribute on the NXdata group, I assume that we are dealing with new-style NXdata. If not, I restored the old code for reading the old style signals.

**Comment by PiRK** [comment]
I tested saving a "zoomed stack region as images" with PyMca 5.1.4, reinstalling PyMca from this branch, and reopening the file. It seems to work fine.

**Comment by vasole** [comment]
The functionality is there and it works with both styles. Thanks!

The points that would be worth to be modified:

- The title is written as a bytes string
- The axes are written as an array of bytes
- One should check the encode attribute is there prior to perform the calls to it

**Comment by vasole** [comment]
The last point refers to, for instance, the buffername parameter.

**Comment by PiRK** [comment]
Regarding axes and title, it seems that actually ALL attributes and datasets are written as bytes.

Should I change all the occurences of `"...".encode("utf-8")` into `numpy.array("...", dtype=h5py.special_dtype(vlen=unicode)))`, or leave it as it is?

**Comment by vasole** [comment]
If I am not mistaken, it should not be necessary to use the vlen trick for things not being a list. A single string should be directly writable. If if its a str written from Python 3 it will be utf-8 and if it is under Python 2 one has to make sure it is written as unicode (with utf-8).

**Comment by PiRK** [comment]
Encoding a string or a unicode in python creates bytes.  H5py has no way of knowing that it was encoded as utf-8, especially if we restrict ourself to the  ASCII charset, so it will just follow its basic strategy of writing bytes as "Variable-length ASCII". 

For single string, we can avoid using the vlen trick by specifically using unicode: `u"..."` 
Then h5py will write them as "Variable-length UTF-8".

**Comment by PiRK** [comment]
It seems that everything is written with the proper encoding now.

I noticed something subtle with h5py: depending on how attrs are written, it is sometimes not allowed to write unicode strings even when it is not a list (via the `attrs.create` API). 
This works:
`h5f["toto"].attrs["toto"] = u"toto"`
This causes an error:
`h5f["toto"].attrs.create("toto", u"toto")`

**Comment by vasole** [comment]
If that problem can be reproduced in recent versions of h5py it should be reported to them.

**Pull request merged**
