### PR TITLE
[setup.py] DATA_DIR_FROM_SETUP and DOC_DIR_FROM_SETUP unicode error

### PR DESCRIPTION
**Pull request by woutdenolf**
issue #460

### CODE REVIEW

**Comment by vasole** [comment]
I guess a smaller change not requiring dealing with bytes or unicode would have been to just make sure an "r" was written in front of the directory string...

**Comment by vasole** [comment]
Please, can you check if replacing in PyMcaDataDir.py the line ``PYMCA_DATA_DIR = 'DATA_DIR_FROM_SETUP'`` by ``PYMCA_DATA_DIR = r'DATA_DIR_FROM_SETUP'``works? I would prefer not to have to guess any encoding.

**Comment by vasole** [comment]
Sorry, given the fact fisx has been using the r trick (see fisx setup.py) for quite some time, I prefer to take the conservative approach of #462

**Comment by woutdenolf** [comment]
At first I thought about using raw strings as well, but doesn't this cause a problem when you actually have non-ascii characters in your path?

**Comment by vasole** [comment]
I do not expect a problem since the path setting is done via the os module. If there is something to be fixed, the fisx module would also have the problem. Most of the times one passes to bytes and the transform works.

image

**Comment by vasole** [comment]
The figure below illustrates the situation I'm afraid off when trying different encodings

image

**Comment by woutdenolf** [comment]
I see, raw strings work just fine. As for trying different encodings: isn't that why one always tries utf8 before latin1? Anyway, problem solved. Thanks!

**Pull request closed without merging**
