### PR TITLE
Fit all curves

### PR DESCRIPTION
**Pull request by PiRK**
- [x] create a widget/GUI, similar to SimpleFitGui and StackSimpleFitAll
 - [x] implement saving fit results to HDF5 (draft function ready but it needs to be modified to save results for one fitted spectrum at a time)
 - [x] implement saving config as INI to HDF5
 - [x] create a Plugin to call the GUI and pass it the necessary data
 - [x] add bg to specfitfunctions

### CODE REVIEW

**Comment by PiRK** [comment]
All the basic components are in place, now we can start testing and improving. 

We still miss an output of the estimation (and therefore of the constraints).

**Comment by vasole** [comment]
- The default functions indeed need a configuration widget to set the search parameters and default constraints.

**Comment by vasole** [comment]
- I got a StringIO error under Python 3 when performing the fit. It is solved by #155.  
- The output needs quite a bit of formatting. We'll discuss it together.
- The copyright date should be 2018 for a new module created this year.

**Comment by PiRK** [comment]
https://github.com/vasole/pymca/pull/146/commits/5ead67f8236d764941eb2af7a5ba665bf134db5b seems to fix my issue with the configuration being ignored.
But we need to check that this is a correct fix for all fit functions in PyMca, not only SpecfitFunctions.

**Comment by vasole** [comment]
Without looking into details, I would say that if we return a dictionary when calling the configuration without arguments we should also send back a dictionary as input.

**Pull request merged**
