### PR TITLE
[packaging] Add input file

### LINKED ISSUE #395: [desktop] desktop-mime-but-no-exec-code
Hello it seems that the Exec command line miss a %F in order to give the file  to the application.

### PR DESCRIPTION
**Pull request by vasole**
closes #395

### CODE REVIEW

**Comment by picca** [comment]
No :)), but maybe there is a way to explain this :)

**Comment by picca** [comment]
https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by vasole** [comment]
OK. I think we are missing a .desktop file for the pymcapostbatch and/or rgbcorrelator.

They are the same script. I guess we should create just one of them.

**Comment by vasole** [comment]
See #397

**Pull request merged**
