### PR TITLE
Update documentaion for Windows stand-alone app

### PR DESCRIPTION
**Pull request by mretegan**
Fix for #1093

### CODE REVIEW

**Comment by vasole** [comment]
That only happens in freshly installed machines where no other C++ application has been installed.

It is not needed to install the runtime systematically. Please, can you specify something like "in case of crash on startup, please make sure that..."

**Comment by mretegan** [comment]
Done. Feel free to change as you wish. The way it was before was causing issues with the new beamline computers.

**Comment by vasole** [comment]
> Done. Feel free to change as you wish. The way it was before was causing issues with the new beamline computers.

I guess the same issue would apply to the `silx`  binary.

**Comment by mretegan** [comment]
Probably, but silx is not a de facto application on ESRF beamline computers, and I assume the majority of people are using PyMca instead of silx for looking at data files.

**Pull request merged**
