### PR TITLE
Setup simplification

### PR DESCRIPTION
**Pull request by PiRK**
Modernize and simplify the setup file. Address #137

### CODE REVIEW

**Comment by PiRK** [comment]
At this stage, tests are required:

Standard installations:
 - [ ] `pip install .
 - [ ] `python setup.py install`

Debian packaging related commands:
 - [ ] `PYMCA_DATA_DIR=/usr/share/pymca PYMCA_DOC_DIR=/usr/share/pymca python setup.py install_data --root /tmp/toto`
 - [ ] `PYMCA_DATA_DIR=/usr/share/pymca PYMCA_DOC_DIR=/usr/share/pymca python setup.py install_man -d /tmp/pierre` 
 - [ ] `PYMCA_DATA_DIR=/usr/share/pymca PYMCA_DOC_DIR=/usr/share/pymca python setup.py install_scripts -d /tmp/pierre`

Frozen binary related commands:
 - [ ]  `python setup.py install --distutils --install-lib /tmp/toto/lib  --install-data /tmp/toto/data --install-scripts /tmp/toto/scripts`

**Comment by PiRK** [comment]
The last command (frozen binary) duplicates the data, for an unknown reason. 
```

$ ls /tmp/toto/data/PyMca5/PyMcaData/
attdata        EXAFS_Cu.dat  KShellRatesScofieldHS.dat  LICENSE.LGPL             LShellRatesScofieldHS.dat  Scofield1973.dict
changelog.txt  EXAFS_Ge.dat  LICENSE                    LICENSE.MIT              McaTheory.cfg              XRFSpectrum.mca
EPDL97         HTML          LICENSE.GPL                LShellRatesCampbell.dat  PyMcaSplashImage.png

$  ls /tmp/toto/lib/PyMca5/PyMcaData
attdata       EXAFS_Ge.dat  __init__.py   KShellRatesScofieldHS.dat  LShellRatesScofieldHS.dat  PyMcaSplashImage.png  XRFSpectrum.mca
EXAFS_Cu.dat  HTML          __init__.pyc  LShellRatesCampbell.dat    McaTheory.cfg              Scofield1973.dict

```

**Comment by PiRK** [comment]
`python setup.py install --user` does not patch the `PyMcaDataDir.py` file correctly, but it still works because of https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaDataDir.py#L40.

The problem is the additional egg directory generated on my machine with my version of setuptools: /users/knobel/.local/lib/python2.7/site-packages/**PyMca5-5.2.2-py2.7-linux-x86_64.egg**/PyMca5/PyMcaData

**Comment by PiRK** [comment]
The rest of the command work, but tomorrow I should test with the debian packaging script on a clean debian machine, and with the frozen binary scripts on Windows and Mac.

**Comment by vasole** [comment]
The egg problem is not so serious. I guess if we can recommend to use ``pip install --user``. Probably we were having the same problem in the past whenever setuptools was used:

https://stackoverflow.com/questions/6301003/stopping-setup-py-from-installing-as-egg

**Comment by vasole** [comment]
I have to admit that previously I was always using distutils while using setuptools only when generating wheels.

**Comment by PiRK** [comment]
More tests: 

 - [ ] `python cx_setup.py install` (tested on Windows, python 2.7)

**Comment by PiRK** [comment]
No success with p2app on the MacBook. But it's probably because I don't know how to use it. 
```
creating build/bdist.macosx-10.12-intel/python2.7-standalone/app/Frameworks
Traceback (most recent call last):
  File "py2app_setup.py", line 85, in <module>
    options={'py2app':PY2APP_OPTIONS}
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/py2app/build_app.py", line 553, in run
    self._run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/py2app/build_app.py", line 741, in _run
    self.run_normal()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/py2app/build_app.py", line 812, in run_normal
    mf = self.get_modulefinder()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/py2app/build_app.py", line 691, in get_modulefinder
    debug=debug,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/modulegraph/find_modules.py", line 274, in find_modules
    find_needed_modules(mf, scripts, includes, packages)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/modulegraph/find_modules.py", line 199, in find_needed_modules
    path = m.packagepath[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by vasole** [comment]
On what machine did you try to run py2app? I recall having to patch modulegraph to deal with the case of trying to access None...

**Comment by PiRK** [comment]
I used the MacBook Pro sitting on Thomas' desk.

**Comment by vasole** [comment]
Ok. Not surprising then. In addition, you were using system's python and not python.org python. I am going to test on the reference computer.

**Pull request merged**
