### PR TITLE
[5.3]McaWindow

### LINKED ISSUE #114: [silx] force silx > 0.6.0 when available in Debian
Related to #109. 

Important bugfixes will be released in `0.6.1`.

Do it in Debian packaging scripts and setup.py

### PR DESCRIPTION
**Pull request by PiRK**
Closes #114. Finalizes #103.

TODO: more testing, handle ROI events.

### CODE REVIEW

**Comment by vasole** [comment]
The ROI events are indeed mandatory because they are needed by PyMca ROI Tool (aka. QStackWidget.py)

**Comment by PiRK** [comment]
This seems to work reasonably well. But it is hard to test it properly in QStackWidget as long as MaskImageWidget is not fixed, due to all the warnings it generates.

I will start working on MaskImageWidget in a different pull request. This one can be merged but more testing should be done later.

**Comment by vasole** [comment]
Please solve the conflicts.

**Comment by PiRK** [comment]
I rebased the branch. It can be merged, now.

**Pull request merged**
