### PR TITLE
H5fastfit

### PR DESCRIPTION
**Pull request by woutdenolf**
Part of issue  #180: HDF5 output for fast fitting
- Nexus utils for saving + unit tests
- Optional output formats: edf, csv, tiff, h5
- Optional diagnostics: data, model, residuals (not in GUI)
- Output naming conventions (compatible with old convention):
    For HDF5: dir/root.h5::/entry/process
    For others: dir/root/entry.edf
    Defaults (same as before):
         root = 'IMAGES'
         entry = 'images'
fastfitdialog
- Add bootstrap for development
- Share saving routine between GUI and script
- Refactor core Fast Fitting routine for readability

### CODE REVIEW

**Comment by vasole** [comment]
The fast fit tries to be economic in memory usage and it is expected to works even with HDF5 datasets not fitting into memory. When generating the fit and residuals matrices, you seem to assume that twice the size of the actual map is going to fit into memory when even the map can be still lying on disk.

I would recommend to check if the memory can be allocated and, if not, proceed as if having selected HDF5 output in order to map the output arrays and fill them.

**Comment by woutdenolf** [comment]
I cannot reproduce the Travis errors of this PR:
 https://travis-ci.org/woutdenolf/pymca/builds/483922089
or locally with the same version of python (3.6.3) and numpy (1.16.0)

**Comment by vasole** [comment]
Line 271 in StackInfoTest. You are modifying the variable "values" over which you are iterating. At least in the past some versions of python complained about it. I think it would be better to use different names.

**Comment by vasole** [comment]
McaStackViewTest and NexusUtilsTest are missing in tests/__init__.py

**Comment by woutdenolf** [comment]
Changes:
-  Moved MCA stack access and output to their own modules (McaStackView and FastXRFLinearFitOutput resp.)
-  Handle MCA stacks of any dimension (work is done in McaStackView)
-  Precision: calculations are done in numpy.float and results are saved in numpy.float32 (unless the spectra itemsize > 4, in which case numpy.float64 is used)
-  Add more tests
-  Adapt coding style (e.g. camel case)
-  Small changes to the GUI:
fastfitdialog

**Comment by vasole** [comment]
There are minor things to be changed, but they can go into separate issues.

Great stuff. Thanks a lot.

**Pull request merged**
