### PR TITLE
Reformat README for better formatting

### PR DESCRIPTION
**Pull request by jat255**
Github nicely formats Markdown pages on the landing page for the project, so I just reformatted the existing README into `.md` format, and added a few links and such to make it a little more user-friendly.

### CODE REVIEW

**Comment by jat255** [comment]
Here's how it looks (you can also visit [my fork](https://github.com/jat255/pymca/tree/format_README) to see it for real:

image

**Comment by vasole** [comment]
It is true the file needs formatting. However, I will use the also supported rst format (like I do in other projects like https://github.com/vasole/fisx ). I guess it will be straightforward to adapt your changes to it.

**Comment by jat255** [comment]
Ok, I used `pandoc` to replace the markdown with .rst

**Comment by vasole** [comment]
Thanks. Sorry for the added work.

**Pull request merged**
